# Generated by Django 5.2.4 on 2025-08-05 08:25

import airport.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Airline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(
                    max_length=100,
                    unique=True
                )),
                ("code", models.CharField(
                    max_length=10,
                    unique=True
                )),
                (
                    "founded_year",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2025),
                        ],
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        null=True,
                        upload_to=airport.models.airline_logo_path
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="AirplaneType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(
                    max_length=100,
                    unique=True
                )),
                ("manufacturer", models.CharField(
                    blank=True,
                    max_length=100
                )),
                (
                    "image",
                    models.ImageField(
                        null=True,
                        upload_to=airport.models.airplane_type_image_path
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "airplane_types",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("population", models.PositiveIntegerField(
                    blank=True,
                    null=True
                )),
            ],
            options={
                "verbose_name_plural": "cities",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("timezone", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name_plural": "countries",
            },
        ),
        migrations.CreateModel(
            name="FlightStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("BOARDING", "Boarding"),
                            ("IN_FLIGHT", "In Flight"),
                            ("LANDED", "Landed"),
                            ("DELAYED", "Delayed"),
                            ("CANCELLED", "Cancelled"),
                            ("DIVERTED", "Diverted"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("color_code", models.CharField(blank=True, max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="Gate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=10)),
                (
                    "gate_type",
                    models.CharField(
                        choices=[
                            ("DOMESTIC", "Internal flights"),
                            ("INTERNATIONAL", "International flights"),
                            ("MIXED", "Mixed flights"),
                        ],
                        default="MIXED",
                        max_length=15,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Airplane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "rows",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ]
                    ),
                ),
                (
                    "seats_in_row",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ]
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        max_length=20,
                        unique=True
                    )),
                (
                    "is_active",
                    models.BooleanField(default=True)
                ),
                (
                    "airline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airplanes",
                        to="airport.airline",
                    ),
                ),
                (
                    "airplane_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airplanes",
                        to="airport.airplanetype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "airplanes",
            },
        ),
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("iata_code", models.CharField(
                    blank=True,
                    max_length=3,
                    unique=True
                )),
                ("icao_code", models.CharField(
                    blank=True,
                    max_length=4,
                    unique=True
                )),
                (
                    "closest_big_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airports",
                        to="airport.city",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "airports",
            },
        ),
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="airport.country",
            ),
        ),
        migrations.AddField(
            model_name="airline",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="airlines",
                to="airport.country",
            ),
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                ("flight_number", models.CharField(max_length=10)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "airplane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airport.airplane",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="airport.flightstatus",
                    ),
                ),
                (
                    "arrival_gate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arrival_flights",
                        to="airport.gate",
                    ),
                ),
                (
                    "departure_gate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="departure_flights",
                        to="airport.gate",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "flights",
            },
        ),
        migrations.CreateModel(
            name="Crew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "flights",
                    models.ManyToManyField(blank=True, to="airport.flight")
                ),
            ],
            options={
                "verbose_name_plural": "crews",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10
                    ),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airport.flight"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.IntegerField()),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrival_routes",
                        to="airport.airport",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departure_routes",
                        to="airport.airport",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "routes",
            },
        ),
        migrations.AddField(
            model_name="flight",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="airport.route"
            ),
        ),
        migrations.CreateModel(
            name="Terminal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Max passengers q-ty per hour"
                    ),
                ),
                ("is_international", models.BooleanField(default=False)),
                ("opened_date", models.DateField(blank=True, null=True)),
                (
                    "airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terminals",
                        to="airport.airport",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gate",
            name="terminal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gates",
                to="airport.terminal",
            ),
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ]
                    ),
                ),
                (
                    "seat",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ]
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True
                    ),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airport.flight"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airport.order"
                    ),
                ),
            ],
            options={
                "ordering": ["row", "seat"],
            },
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.UniqueConstraint(
                fields=("name", "country"),
                name="unique_city_country"
            ),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["source", "destination"],
                name="airport_rou_source__5c8f4c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="route",
            constraint=models.UniqueConstraint(
                fields=("source", "destination"),
                name="unique_route"
            ),
        ),
        migrations.AddConstraint(
            model_name="route",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "source",
                    models.F("destination")),
                    _negated=True),
                name="different_airports",
            ),
        ),
        migrations.AddConstraint(
            model_name="flight",
            constraint=models.UniqueConstraint(
                fields=("flight_number", "departure_time"),
                name="unique_flight_number_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="flight",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "departure_time__lt",
                    models.F("arrival_time")
                )),
                name="departure_before_arrival",
            ),
        ),
        migrations.AddConstraint(
            model_name="terminal",
            constraint=models.UniqueConstraint(
                fields=("name", "airport"),
                name="unique_terminal_airport"
            ),
        ),
        migrations.AddConstraint(
            model_name="gate",
            constraint=models.UniqueConstraint(
                fields=("number", "terminal"),
                name="unique_gate_terminal"
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("row", "seat", "flight"),
                name="unique_ticket_row_seat_flight"
            ),
        ),
    ]
