# Generated by Django 5.2.4 on 2025-08-11 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airline",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="airplane",
            options={"ordering": ["name"], "verbose_name_plural": "airplanes"},
        ),
        migrations.AlterModelOptions(
            name="airplanetype",
            options={"ordering": ["name"], "verbose_name_plural": "airplane_types"},
        ),
        migrations.AlterModelOptions(
            name="airport",
            options={"ordering": ("id",), "verbose_name_plural": "airports"},
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"ordering": ("id",), "verbose_name_plural": "cities"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ("id",), "verbose_name_plural": "countries"},
        ),
        migrations.AlterModelOptions(
            name="flight",
            options={"ordering": ["id"], "verbose_name_plural": "flights"},
        ),
        migrations.AlterModelOptions(
            name="flightstatus",
            options={"verbose_name_plural": "flight statuses"},
        ),
        migrations.AlterModelOptions(
            name="gate",
            options={"ordering": ("number",)},
        ),
        migrations.AlterModelOptions(
            name="route",
            options={"ordering": ("id",), "verbose_name_plural": "routes"},
        ),
        migrations.AlterModelOptions(
            name="terminal",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"], "verbose_name_plural": "tickets"},
        ),
        migrations.AddField(
            model_name="city",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="flight",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="flightstatus",
            name="name",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("BOARDING", "Boarding"),
                    ("IN_FLIGHT", "In Flight"),
                    ("LANDED", "Landed"),
                    ("DELAYED", "Delayed"),
                    ("CANCELLED", "Cancelled"),
                    ("DIVERTED", "Diverted"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="distance",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="airport.flight",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="airport.order",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
